### PR TITLE
Vue 3 support

### PR DESCRIPTION
**Pull request by iBobik**
I've merged all the work in geospoc/v-mapbox from the last year with Vue 3 compatibility done in older PR #264.

It still is not working, more debugging is needed, but it is behind my skills in TypeScript, so I will need help.

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
Looks promising @iBobik, have you given a shot at  #714 though, I’ve completely refactored the code to ensure it works with Vue 2 & Vue 3 using Vue-demi.

just having issues in making the geojson layers persist on base map change

**Comment by iBobik** [comment]
@vinayakkulkarni Very nice, it is much better than my try. I will test it in my project next sprint.

**Comment by vinayakkulkarni** [comment]
> @vinayakkulkarni Very nice, it is much better than my try. I will test it in my project next sprint.

You can try out the `next` version by installing `npm i v-mapbox@3`

**Comment by uncle-samm** [comment]
> > @vinayakkulkarni Very nice, it is much better than my try. I will test it in my project next sprint.
> 
> You can try out the `next` version by installing `npm i v-mapbox@3`

Any docs to use this? Tried it with nuxt3 no success yet. even with ssr disabled.

**Comment by vinayakkulkarni** [comment]
Closing this as v3.x supports Vue 3.x

**Pull request closed without merging**
