### PR TITLE
Vue 3 migration

### PR DESCRIPTION
**Pull request by ropez**
I managed to get this working in Vue 3, at least for our current use-case, which is fairly simple.

Not sure what your take on this. I saw you had some plans for typescript and composition API in the refactor/vue-3 branch. This does not follow such plans, but just tries to make everything work with as few changes as possible:

- The pattern of provide/inject doesn't seem to work in Vue 3, so I had to wrap the injected references into a "context" object
- Event mapping no longer filter events by what is included in `$listeners` (since `$listeners` doesn't exist anymore). While it might have been possible to search for `onEvent` patterns in $props, I figured is seems like a premature optimization, and just map all known events.

We will probably use this patched version in our system for now. Please let me know if this is something you will consider to include in the "official" plans for Vue 3, and if there's something more you'd like me to do.

### CODE REVIEW

**Comment by ropez** [comment]
BTW, also to make it build, I had to change the order in `rollup.config.js` and `rollup.config.min.js`, so that `vue` comes before `babel` in the plugins list. Not sure if you're aware of this.

Also, to make the package work in our application, when I include the CSS file, I had to add an empty `postcss.config.js` in this repo.

**Comment by eshimischi** [comment]
Provide/Inject in Vue 3 https://blog.logrocket.com/provide-inject-vue-js-3-composition-api/ or https://v3.vuejs.org/guide/composition-api-provide-inject.html

**Comment by vinayakkulkarni** [comment]
I'll look into this over the weekend

**Comment by iBobik** [comment]
Hello,
I tried to refresh your work in #732, but I need help because it is behind my skills to finish it.

**Comment by vinayakkulkarni** [comment]
- [x] Closing this cause refactoring using Vue 3 is in the draft PR – #714

**Pull request closed without merging**
