### PR TITLE
feat: add className option to popup

### PR DESCRIPTION
**Pull request by Kyle123**
Hi, not sure if you're open to pull requests

I've implemented the `className` option of the popup, this is not reactive

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
@Kyle123: can you please rebase

else, LGTM.

**Comment by Kyle123** [comment]
@vinayakkulkarni  great, should be all up to date now

**Review by vinayakkulkarni — APPROVED** [review]

**Comment by vinayakkulkarni** [comment]
You forgot the apply the classes to the `div` :P 

Fixing it in next PR

**Comment by Kyle123** [comment]
Are you sure it needs it? It will do it by default as long as the property name in Mapbox is the same as the prop as the props are passed straight into the popup init as is.

**Pull request merged**
